channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - opencv=4.10.0           # from conda (faster, fewer build hassles)
  - pip=25.0
  - pip:
      - numpy==1.26.2
      - pandas==2.2.3
      - scipy==1.15.3
      - scikit-learn==1.7.0
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - seaborn==0.13.2
      - tqdm==4.67.1
      - rich==14.0.0
      - regex==2024.11.6
      - einops==0.8.1
      - timm==0.4.12
      - transformers==4.50.3
      - tokenizers==0.21.1
      - safetensors==0.5.3
      - torchvision==0.16.1
      - torchaudio==2.1.1
      # Other libs you used
      - ray==2.43.0
      - ml-collections==1.0.0
      - umap==0.1.1
      - torchsummaryx==1.3.0
      - ninja==1.11.1.4

      - causal-conv1d @ file:///home/zhulianghui/VisionProjects/mamba/lib/causal_conv1d-1.0.0%2Bcu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl#sha256=79a4bab633ebff031e615d5e8ba396b0dc0c046f4406980ee238fb86a9090038
      - mamba-ssm @ file:///home/zhulianghui/VisionProjects/mamba/lib/mamba_ssm-1.0.1%2Bcu118torch2.1cxx11abiFALSE-cp310-cp310-linux_x86_64.whl#sha256=71ad1b1eafb05a6e8a41fd82e046fe85511d6378fa3a583e55215b6aa1d65ab9

